# Generated by Django 4.0.4 on 2022-05-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_comments', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Fashion', 'Fashion')], max_length=64, null=True),
        ),
    ]
