# Generated by Django 4.0.4 on 2022-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='media/default_img.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=64, null=True),
        ),
    ]
