# Generated by Django 4.1 on 2022-09-04 18:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_img_url_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Home', 'Home'), ('Misc', 'Misc'), ('Fashion', 'Fashion'), ('Other', 'Other'), ('Electronics', 'Electronics')], default='Misc', max_length=64, null=True),
        ),
    ]
