# Generated by Django 4.0.4 on 2022-05-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Fashion', 'Fashion')], max_length=64, null=True),
        ),
    ]
