# Generated by Django 4.0.4 on 2022-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category_alter_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Other', 'Other'), ('Fashion', 'Fashion')], max_length=64, null=True),
        ),
    ]
