# Generated by Django 4.1 on 2022-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_bidding_on_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Misc', 'Misc'), ('Other', 'Other'), ('Home', 'Home'), ('Toys', 'Toys')], default='Misc', max_length=64, null=True),
        ),
    ]
