# Generated by Django 4.0.4 on 2022-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Home', 'Home'), ('Toys', 'Toys'), ('Other', 'Other'), ('Electronics', 'Electronics')], max_length=64, null=True),
        ),
    ]
