# Generated by Django 4.0.4 on 2022-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], max_length=64, null=True),
        ),
    ]
