# Generated by Django 4.0.4 on 2022-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Home', 'Home')], max_length=64, null=True),
        ),
    ]
