# Generated by Django 4.1 on 2022-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Misc', 'Misc'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Other', 'Other'), ('Fashion', 'Fashion'), ('Toys', 'Toys')], default='Misc', max_length=64, null=True),
        ),
    ]
