# Generated by Django 4.1 on 2022-08-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Toys', 'Toys'), ('Other', 'Other'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion')], max_length=64, null=True),
        ),
    ]
