# Generated by Django 4.1 on 2022-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Misc', 'Misc'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Other', 'Other')], default='Misc', max_length=64, null=True),
        ),
    ]
