# Generated by Django 4.1 on 2022-09-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_alter_bid_bidder_alter_comment_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auctions.category'),
        ),
    ]
